In [39]:
% matplotlib inline
from PIL import Image
import numpy as np
from PIL import ImageFilter
import matplotlib.pyplot as plt
from skimage.filters.rank import entropy
from skimage.morphology import disk

In [88]:
image=Image.open("C:/test/0.jpg")
width, height = image.size
X= np.array(image).reshape(-1,1)

In [103]:
#im1 = image.filter(ImageFilter.GaussianBlur(radius=12))
#im2 = image.filter(ImageFilter.MedianFilter(size=15))
#im3 = image.filter(ImageFilter.MinFilter(size=3))
#im4 = image.filter(ImageFilter.MaxFilter(size=3))
#im5 = image.filter(ImageFilter.ModeFilter(size=13))
img6 = entropy(X, disk(10))

In [104]:
img6 = img6.reshape(-1,3)
print (img6)

[[ 3.45943162  3.5849625   3.70043972]
 [ 3.80735492  3.9068906   4.        ]
 [ 4.08746284  4.169925    4.24792751]
 ..., 
 [ 4.0374012   4.05881389  3.96981578]
 [ 4.          3.9068906   3.80735492]
 [ 3.70043972  3.5849625   3.45943162]]
