In [7]:
from skimage.feature import structure_tensor,structure_tensor_eigvals
from PIL import Image
import numpy as np

In [8]:
image = Image.open('C:/test/0.jpg')
y= np.asarray(image,dtype=np.float64).reshape(-1,3)
Axx, Axy, Ayy = structure_tensor(y, sigma=25)
Hrr = Axx
Hcc = Ayy
Hrc = Axy
S0 = structure_tensor_eigvals(Axx, Axy, Ayy)[0]
S1= structure_tensor_eigvals(Axx, Axy, Ayy)[1]

In [20]:
#print (S1)

[[ 342.79990869  342.99599512  342.64395759]
 [ 343.54203541  343.73883748  343.3863291 ]
 [ 343.78395014  343.98119049  343.62873369]
 ..., 
 [ 462.7281054   463.04161164  462.61514727]
 [ 463.59655102  463.91057379  463.48323651]
 [ 463.73701953  464.05106685  463.62352879]]


In [9]:
module = ((Hrr*Hrr)+(Hrc*Hrc)+(Hcc*Hcc))**(1/2.0)

In [10]:
Trace = (Hrr+Hcc)

In [11]:
Determinant = ((Hrr*Hcc)-(Hrc*Hrc))

In [12]:
t = ((4*Hrc*Hrc)+((Hrr-Hcc)**(2.0)))
Orientation = ((np.arccos(t))/2)

C:\Users\69654\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arccos
  


In [21]:
j= ((2*Hrc)/(Hcc-Hrr))
jj= ((np.arctan(j))/2)
J= np.degrees (jj)

In [13]:
gamma = ((1**(3/4.0))**(4.0))*(((Hrr-Hcc)**(2.0)))*((4*Hrc*Hrc)+((Hrr-Hcc)**(2.0)))

In [14]:
gamma_0 = (((1**(3/4.0))**(2.0))*((4*Hrc*Hrc)+((Hrr-Hcc)**(2.0))))